"""Add wallet system

Revision ID: 20260331_wallet
Revises: 20260323_120000
Create Date: 2026-03-31 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20260331_wallet'
down_revision = '20260323_120000'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create wallets table
    op.create_table('wallets',
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('user_id', sa.Uuid(), nullable=False),
                    sa.Column('balance', sa.Numeric(
                        precision=12, scale=2), nullable=False),
                    sa.Column('locked_balance', sa.Numeric(
                        precision=12, scale=2), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['user_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('user_id', name='uq_wallets_user_id')
                    )
    op.create_index(op.f('ix_wallets_user_id'),
                    'wallets', ['user_id'], unique=False)

    # Create wallet_transactions table
    op.create_table('wallet_transactions',
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('wallet_id', sa.Uuid(), nullable=False),
                    sa.Column('amount', sa.Numeric(
                        precision=12, scale=2), nullable=False),
                    sa.Column('type', sa.String(length=50), nullable=False),
                    sa.Column('description', sa.String(
                        length=500), nullable=True),
                    sa.Column('order_id', sa.Uuid(), nullable=True),
                    sa.Column('escrow_id', sa.Uuid(), nullable=True),
                    sa.Column('balance_before', sa.Numeric(
                        precision=12, scale=2), nullable=False),
                    sa.Column('balance_after', sa.Numeric(
                        precision=12, scale=2), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['wallet_id'], ['wallets.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['order_id'], ['orders.id'], ondelete='SET NULL'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_wallet_transactions_wallet_id'),
                    'wallet_transactions', ['wallet_id'], unique=False)
    op.create_index(op.f('ix_wallet_transactions_order_id'),
                    'wallet_transactions', ['order_id'], unique=False)
    op.create_index(op.f('ix_wallet_transactions_created_at'),
                    'wallet_transactions', ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(op.f('ix_wallet_transactions_created_at'),
                  table_name='wallet_transactions')
    op.drop_index(op.f('ix_wallet_transactions_order_id'),
                  table_name='wallet_transactions')
    op.drop_index(op.f('ix_wallet_transactions_wallet_id'),
                  table_name='wallet_transactions')
    op.drop_table('wallet_transactions')

    op.drop_index(op.f('ix_wallets_user_id'), table_name='wallets')
    op.drop_table('wallets')

    # ### end Alembic commands ###
