"""Add escrow system

Revision ID: 20260331_escrow
Revises: 20260331_wallet
Create Date: 2026-03-31 00:10:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20260331_escrow'
down_revision = '20260331_wallet'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create escrows table
    op.create_table('escrows',
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('order_id', sa.Uuid(), nullable=False),
                    sa.Column('amount', sa.Numeric(
                        precision=12, scale=2), nullable=False),
                    sa.Column('status', sa.String(length=50), nullable=False),
                    sa.Column('buyer_wallet_id', sa.Uuid(), nullable=False),
                    sa.Column('seller_wallet_id', sa.Uuid(), nullable=False),
                    sa.Column('dispute_reason', sa.String(
                        length=500), nullable=True),
                    sa.Column('dispute_opened_at', sa.DateTime(
                        timezone=True), nullable=True),
                    sa.Column('admin_resolved_by', sa.Uuid(), nullable=True),
                    sa.Column('funded_at', sa.DateTime(
                        timezone=True), nullable=True),
                    sa.Column('release_requested_at', sa.DateTime(
                        timezone=True), nullable=True),
                    sa.Column('released_at', sa.DateTime(
                        timezone=True), nullable=True),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['order_id'], ['orders.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['buyer_wallet_id'], ['wallets.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['seller_wallet_id'], ['wallets.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['admin_resolved_by'], ['users.id'], ondelete='SET NULL'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('order_id', name='uq_escrows_order_id')
                    )
    op.create_index(op.f('ix_escrows_order_id'),
                    'escrows', ['order_id'], unique=False)
    op.create_index(op.f('ix_escrows_buyer_wallet_id'),
                    'escrows', ['buyer_wallet_id'], unique=False)
    op.create_index(op.f('ix_escrows_seller_wallet_id'),
                    'escrows', ['seller_wallet_id'], unique=False)
    op.create_index(op.f('ix_escrows_status'),
                    'escrows', ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(op.f('ix_escrows_status'), table_name='escrows')
    op.drop_index(op.f('ix_escrows_seller_wallet_id'), table_name='escrows')
    op.drop_index(op.f('ix_escrows_buyer_wallet_id'), table_name='escrows')
    op.drop_index(op.f('ix_escrows_order_id'), table_name='escrows')
    op.drop_table('escrows')

    # ### end Alembic commands ###
