"""Add offer, order, review, notification models

Revision ID: 20260323_120000
Revises: 1de4b1ba703e
Create Date: 2026-03-23 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '20260323_120000'
down_revision = '1de4b1ba703e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create offers table
    op.create_table('offers',
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('listing_id', sa.Uuid(), nullable=False),
                    sa.Column('buyer_id', sa.Uuid(), nullable=False),
                    sa.Column('offer_price', sa.Numeric(
                        precision=12, scale=2), nullable=False),
                    sa.Column('status', sa.String(length=50), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ),
                    sa.ForeignKeyConstraint(
                        ['listing_id'], ['listings.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_offers_buyer_id'),
                    'offers', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_offers_listing_id'),
                    'offers', ['listing_id'], unique=False)

    # Create orders table
    op.create_table('orders',
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('buyer_id', sa.Uuid(), nullable=False),
                    sa.Column('seller_id', sa.Uuid(), nullable=False),
                    sa.Column('listing_id', sa.Uuid(), nullable=False),
                    sa.Column('final_price', sa.Numeric(
                        precision=12, scale=2), nullable=False),
                    sa.Column('status', sa.String(length=50), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['buyer_id'], ['users.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['listing_id'], ['listings.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['seller_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_orders_buyer_id'),
                    'orders', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_orders_listing_id'),
                    'orders', ['listing_id'], unique=False)
    op.create_index(op.f('ix_orders_seller_id'),
                    'orders', ['seller_id'], unique=False)

    # Create reviews table
    op.create_table('reviews',
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('order_id', sa.Uuid(), nullable=False),
                    sa.Column('reviewer_id', sa.Uuid(), nullable=False),
                    sa.Column('reviewee_id', sa.Uuid(), nullable=False),
                    sa.Column('rating', sa.Integer(), nullable=False),
                    sa.Column(
                        'comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['order_id'], ['orders.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['reviewee_id'], ['users.id'], ),
                    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('order_id', 'reviewer_id',
                                        name='uq_review_order_reviewer')
                    )
    op.create_index(op.f('ix_reviews_order_id'),
                    'reviews', ['order_id'], unique=False)
    op.create_index(op.f('ix_reviews_reviewee_id'),
                    'reviews', ['reviewee_id'], unique=False)
    op.create_index(op.f('ix_reviews_reviewer_id'),
                    'reviews', ['reviewer_id'], unique=False)

    # Create notifications table
    op.create_table('notifications',
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('user_id', sa.Uuid(), nullable=False),
                    sa.Column('type', sa.String(length=50), nullable=False),
                    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(
                        length=255), nullable=False),
                    sa.Column(
                        'message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('data', sa.JSON(), nullable=False),
                    sa.Column('is_read', sa.Boolean(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['user_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_notifications_user_id'),
                    'notifications', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_reviews_reviewer_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_reviewee_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_order_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_orders_seller_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_listing_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_buyer_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_offers_listing_id'), table_name='offers')
    op.drop_index(op.f('ix_offers_buyer_id'), table_name='offers')
    op.drop_table('offers')
    # ### end Alembic commands ###
