"""add_offer_partial_unique_index

Revision ID: 2899f34aca4a
Revises: fc157c202cf2
Create Date: 2026-06-08 22:06:00.451125

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2899f34aca4a'
down_revision = 'fc157c202cf2'
branch_labels = None
depends_on = None


def table_exists(name: str) -> bool:
    bind = op.get_bind()
    result = bind.execute(
        sa.text(
            "SELECT EXISTS (SELECT 1 FROM information_schema.tables "
            f"WHERE table_name = '{name}')"
        )
    )
    return result.scalar()


def index_exists(index_name: str) -> bool:
    bind = op.get_bind()
    result = bind.execute(
        sa.text(
            "SELECT EXISTS (SELECT 1 FROM pg_indexes "
            f"WHERE indexname = '{index_name}')"
        )
    )
    return result.scalar()


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if table_exists('chat_conversations'):
        op.alter_column('chat_conversations', 'created_at',
                   existing_type=postgresql.TIMESTAMP(timezone=True),
                   nullable=True)
    if table_exists('conversation_participants'):
        op.alter_column('conversation_participants', 'joined_at',
                   existing_type=postgresql.TIMESTAMP(timezone=True),
                   nullable=True)
    if table_exists('messages'):
        op.alter_column('messages', 'created_at',
                   existing_type=postgresql.TIMESTAMP(timezone=True),
                   nullable=True)
    op.create_index('uq_offer_active_per_buyer_listing', 'offers', ['buyer_id', 'listing_id'], unique=True, postgresql_where=sa.text("status IN ('pending', 'countered')"))
    if table_exists('order_events'):
        op.alter_column('order_events', 'created_at',
                   existing_type=postgresql.TIMESTAMP(timezone=True),
                   nullable=True)
    if index_exists('ix_orders_tracking_number'):
        op.drop_index(op.f('ix_orders_tracking_number'), table_name='orders')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if not index_exists('ix_orders_tracking_number'):
        op.create_index(op.f('ix_orders_tracking_number'), 'orders', ['tracking_number'], unique=False)
    if table_exists('order_events'):
        op.alter_column('order_events', 'created_at',
                   existing_type=postgresql.TIMESTAMP(timezone=True),
                   nullable=False)
    op.drop_index('uq_offer_active_per_buyer_listing', table_name='offers', postgresql_where=sa.text("status IN ('pending', 'countered')"))
    if table_exists('messages'):
        op.alter_column('messages', 'created_at',
                   existing_type=postgresql.TIMESTAMP(timezone=True),
                   nullable=False)
    if table_exists('conversation_participants'):
        op.alter_column('conversation_participants', 'joined_at',
                   existing_type=postgresql.TIMESTAMP(timezone=True),
                   nullable=False)
    if table_exists('chat_conversations'):
        op.alter_column('chat_conversations', 'created_at',
                   existing_type=postgresql.TIMESTAMP(timezone=True),
                   nullable=False)
    # ### end Alembic commands ###
