"""sync models from BE_plan

Revision ID: d42d9cf0b040
Revises: 20260331_escrow
Create Date: 2026-05-17 18:42:14.128459

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd42d9cf0b040'
down_revision = '20260331_escrow'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_static_contents_key'), table_name='static_contents')
    op.drop_table('static_contents')
    op.drop_table('item')
    op.drop_constraint(op.f('categories_parent_id_fkey'),
                       'categories', type_='foreignkey')
    op.drop_column('categories', 'parent_id')
    op.add_column('escrows', sa.Column(
        'admin_notes', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True))
    op.add_column('escrows', sa.Column('resolution_reason',
                  sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    op.add_column('escrows', sa.Column(
        'resolved_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('escrows', sa.Column('dispute_status',
                  sa.String(length=50), nullable=True))
    op.alter_column('escrows', 'status',
                    existing_type=sa.VARCHAR(length=50),
                    nullable=True)
    op.drop_index(op.f('ix_escrows_status'), table_name='escrows')
    op.drop_constraint(op.f('uq_escrows_order_id'), 'escrows', type_='unique')
    op.drop_index(op.f('ix_escrows_order_id'), table_name='escrows')
    op.create_index(op.f('ix_escrows_order_id'),
                    'escrows', ['order_id'], unique=True)
    op.drop_constraint(op.f('escrows_seller_wallet_id_fkey'),
                       'escrows', type_='foreignkey')
    op.drop_constraint(op.f('escrows_buyer_wallet_id_fkey'),
                       'escrows', type_='foreignkey')
    op.create_foreign_key(None, 'escrows', 'wallets',
                          ['buyer_wallet_id'], ['id'])
    op.create_foreign_key(None, 'escrows', 'wallets', [
                          'seller_wallet_id'], ['id'])
    op.add_column('listings', sa.Column('rejection_reason',
                  sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True))
    op.add_column('listings', sa.Column(
        'view_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('listings', sa.Column(
        'save_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('listings', sa.Column(
        'is_featured', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('listings', sa.Column('published_at',
                  sa.DateTime(timezone=True), nullable=True))
    op.add_column('listings', sa.Column('location_summary',
                  sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.alter_column('notifications', 'type',
                    existing_type=sa.VARCHAR(length=50),
                    nullable=True)
    op.alter_column('notifications', 'data',
                    existing_type=postgresql.JSON(astext_type=sa.Text()),
                    nullable=True)
    op.alter_column('notifications', 'created_at',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    type_=sa.DateTime(),
                    existing_nullable=False)
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.alter_column('offers', 'status',
                    existing_type=sa.VARCHAR(length=50),
                    nullable=True)
    op.alter_column('offers', 'created_at',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    type_=sa.DateTime(),
                    existing_nullable=False)
    op.alter_column('offers', 'updated_at',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    type_=sa.DateTime(),
                    existing_nullable=False)
    op.drop_index(op.f('ix_offers_buyer_id'), table_name='offers')
    op.drop_index(op.f('ix_offers_listing_id'), table_name='offers')
    op.alter_column('orders', 'status',
                    existing_type=sa.VARCHAR(length=50),
                    nullable=True)
    op.alter_column('orders', 'created_at',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    type_=sa.DateTime(),
                    existing_nullable=False)
    op.alter_column('orders', 'updated_at',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    type_=sa.DateTime(),
                    existing_nullable=False)
    op.drop_index(op.f('ix_orders_buyer_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_listing_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_seller_id'), table_name='orders')
    op.alter_column('reviews', 'created_at',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    type_=sa.DateTime(),
                    existing_nullable=False)
    op.drop_index(op.f('ix_reviews_order_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_reviewee_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_reviewer_id'), table_name='reviews')
    op.add_column('users', sa.Column(
        'shop_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('users', sa.Column('shop_description',
                  sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True))
    op.add_column('users', sa.Column(
        'shop_verified', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column(
        'shop_response_time', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column(
        'last_active_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column(
        'follower_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column(
        'following_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column(
        'sales_count', sa.Integer(), server_default='0', nullable=False))
    op.alter_column('wallet_transactions', 'type',
                    existing_type=sa.VARCHAR(length=50),
                    nullable=True)
    op.drop_index(op.f('ix_wallet_transactions_order_id'),
                  table_name='wallet_transactions')
    op.drop_constraint(op.f('uq_wallets_user_id'), 'wallets', type_='unique')
    op.drop_index(op.f('ix_wallets_user_id'), table_name='wallets')
    op.create_index(op.f('ix_wallets_user_id'),
                    'wallets', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wallets_user_id'), table_name='wallets')
    op.create_index(op.f('ix_wallets_user_id'),
                    'wallets', ['user_id'], unique=False)
    op.create_unique_constraint(op.f('uq_wallets_user_id'), 'wallets', [
                                'user_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_wallet_transactions_order_id'),
                    'wallet_transactions', ['order_id'], unique=False)
    op.alter_column('wallet_transactions', 'type',
                    existing_type=sa.VARCHAR(length=50),
                    nullable=False)
    op.drop_column('users', 'sales_count')
    op.drop_column('users', 'following_count')
    op.drop_column('users', 'follower_count')
    op.drop_column('users', 'last_active_at')
    op.drop_column('users', 'shop_response_time')
    op.drop_column('users', 'shop_verified')
    op.drop_column('users', 'shop_description')
    op.drop_column('users', 'shop_name')
    op.create_index(op.f('ix_reviews_reviewer_id'),
                    'reviews', ['reviewer_id'], unique=False)
    op.create_index(op.f('ix_reviews_reviewee_id'),
                    'reviews', ['reviewee_id'], unique=False)
    op.create_index(op.f('ix_reviews_order_id'),
                    'reviews', ['order_id'], unique=False)
    op.alter_column('reviews', 'created_at',
                    existing_type=sa.DateTime(),
                    type_=postgresql.TIMESTAMP(timezone=True),
                    existing_nullable=False)
    op.create_index(op.f('ix_orders_seller_id'),
                    'orders', ['seller_id'], unique=False)
    op.create_index(op.f('ix_orders_listing_id'),
                    'orders', ['listing_id'], unique=False)
    op.create_index(op.f('ix_orders_buyer_id'),
                    'orders', ['buyer_id'], unique=False)
    op.alter_column('orders', 'updated_at',
                    existing_type=sa.DateTime(),
                    type_=postgresql.TIMESTAMP(timezone=True),
                    existing_nullable=False)
    op.alter_column('orders', 'created_at',
                    existing_type=sa.DateTime(),
                    type_=postgresql.TIMESTAMP(timezone=True),
                    existing_nullable=False)
    op.alter_column('orders', 'status',
                    existing_type=sa.VARCHAR(length=50),
                    nullable=False)
    op.create_index(op.f('ix_offers_listing_id'),
                    'offers', ['listing_id'], unique=False)
    op.create_index(op.f('ix_offers_buyer_id'),
                    'offers', ['buyer_id'], unique=False)
    op.alter_column('offers', 'updated_at',
                    existing_type=sa.DateTime(),
                    type_=postgresql.TIMESTAMP(timezone=True),
                    existing_nullable=False)
    op.alter_column('offers', 'created_at',
                    existing_type=sa.DateTime(),
                    type_=postgresql.TIMESTAMP(timezone=True),
                    existing_nullable=False)
    op.alter_column('offers', 'status',
                    existing_type=sa.VARCHAR(length=50),
                    nullable=False)
    op.create_index(op.f('ix_notifications_user_id'),
                    'notifications', ['user_id'], unique=False)
    op.alter_column('notifications', 'created_at',
                    existing_type=sa.DateTime(),
                    type_=postgresql.TIMESTAMP(timezone=True),
                    existing_nullable=False)
    op.alter_column('notifications', 'data',
                    existing_type=postgresql.JSON(astext_type=sa.Text()),
                    nullable=False)
    op.alter_column('notifications', 'type',
                    existing_type=sa.VARCHAR(length=50),
                    nullable=False)
    op.drop_column('listings', 'location_summary')
    op.drop_column('listings', 'published_at')
    op.drop_column('listings', 'is_featured')
    op.drop_column('listings', 'save_count')
    op.drop_column('listings', 'view_count')
    op.drop_column('listings', 'rejection_reason')
    op.drop_constraint(None, 'escrows', type_='foreignkey')
    op.drop_constraint(None, 'escrows', type_='foreignkey')
    op.create_foreign_key(op.f('escrows_buyer_wallet_id_fkey'), 'escrows', 'wallets', [
                          'buyer_wallet_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('escrows_seller_wallet_id_fkey'), 'escrows', 'wallets', [
                          'seller_wallet_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_escrows_order_id'), table_name='escrows')
    op.create_index(op.f('ix_escrows_order_id'),
                    'escrows', ['order_id'], unique=False)
    op.create_unique_constraint(op.f('uq_escrows_order_id'), 'escrows', [
                                'order_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_escrows_status'),
                    'escrows', ['status'], unique=False)
    op.alter_column('escrows', 'status',
                    existing_type=sa.VARCHAR(length=50),
                    nullable=False)
    op.drop_column('escrows', 'dispute_status')
    op.drop_column('escrows', 'resolved_at')
    op.drop_column('escrows', 'resolution_reason')
    op.drop_column('escrows', 'admin_notes')
    op.add_column('categories', sa.Column(
        'parent_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('categories_parent_id_fkey'),
                          'categories', 'categories', ['parent_id'], ['id'])
    op.create_table('item',
                    sa.Column('title', sa.VARCHAR(length=255),
                              autoincrement=False, nullable=False),
                    sa.Column('description', sa.VARCHAR(length=255),
                              autoincrement=False, nullable=True),
                    sa.Column('id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(
                        timezone=True), autoincrement=False, nullable=True),
                    sa.Column('owner_id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f(
                        'item_owner_id_fkey'), ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id', name=op.f('item_pkey'))
                    )
    op.create_table('static_contents',
                    sa.Column('id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('key', sa.VARCHAR(length=100),
                              autoincrement=False, nullable=False),
                    sa.Column('title', sa.VARCHAR(length=255),
                              autoincrement=False, nullable=False),
                    sa.Column('body', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('locale', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('version', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(),
                              autoincrement=False, nullable=False),
                    sa.Column('updated_at', postgresql.TIMESTAMP(),
                              autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint(
                        'id', name=op.f('static_contents_pkey'))
                    )
    op.create_index(op.f('ix_static_contents_key'),
                    'static_contents', ['key'], unique=False)
    # ### end Alembic commands ###
