"""sync_orders_columns

Revision ID: fc157c202cf2
Revises: 20260605_return
Create Date: 2026-06-08 14:28:16.911969

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'fc157c202cf2'
down_revision = '20260605_return'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('order_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'offers', 'orders', ['order_id'], ['id'], ondelete='SET NULL')
    op.add_column('orders', sa.Column('offer_id', sa.Uuid(), nullable=True))
    op.add_column('orders', sa.Column('delivered_at_record', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('auto_complete_at', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('auto_release_at', sa.DateTime(), nullable=True))
    op.alter_column('orders', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('PENDING', 'CONFIRMED', 'SHIPPING', 'DELIVERED', 'DELIVERY_FAILED', 'RETURNING', 'RETURNED', 'COMPLETED', 'CANCELLED', name='orderstatus'),
               nullable=False,
               postgresql_using="upper(status)::orderstatus")
    op.alter_column('orders', 'payment_method', server_default=None)
    op.alter_column('orders', 'payment_method',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('WALLET', 'COD', name='paymentmethod'),
               existing_nullable=False,
               postgresql_using="upper(payment_method)::paymentmethod")
    op.alter_column('orders', 'payment_method',
               server_default=sa.text("'WALLET'::paymentmethod"))
    op.drop_index(op.f('ix_orders_tracking_number'), table_name='orders')
    op.create_index(op.f('ix_orders_buyer_id'), 'orders', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_orders_seller_id'), 'orders', ['seller_id'], unique=False)
    op.drop_constraint(op.f('orders_listing_id_fkey'), 'orders', type_='foreignkey')
    op.drop_constraint(op.f('orders_seller_id_fkey'), 'orders', type_='foreignkey')
    op.drop_constraint(op.f('orders_buyer_id_fkey'), 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'listings', ['listing_id'], ['id'])
    op.create_foreign_key(None, 'orders', 'offers', ['offer_id'], ['id'])
    op.create_foreign_key(None, 'orders', 'users', ['seller_id'], ['id'])
    op.create_foreign_key(None, 'orders', 'users', ['buyer_id'], ['id'])
    op.alter_column('wallet_transactions', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'completed'::character varying"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wallet_transactions', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'completed'::character varying"))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key(op.f('orders_buyer_id_fkey'), 'orders', 'users', ['buyer_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('orders_seller_id_fkey'), 'orders', 'users', ['seller_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('orders_listing_id_fkey'), 'orders', 'listings', ['listing_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_orders_seller_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_buyer_id'), table_name='orders')
    op.create_index(op.f('ix_orders_tracking_number'), 'orders', ['tracking_number'], unique=False)
    op.alter_column('orders', 'payment_method',
               existing_type=sa.Enum('WALLET', 'COD', name='paymentmethod'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'wallet'::character varying"))
    op.alter_column('orders', 'status',
               existing_type=sa.Enum('PENDING', 'CONFIRMED', 'SHIPPING', 'DELIVERED', 'DELIVERY_FAILED', 'RETURNING', 'RETURNED', 'COMPLETED', 'CANCELLED', name='orderstatus'),
               type_=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('orders', 'auto_release_at')
    op.drop_column('orders', 'auto_complete_at')
    op.drop_column('orders', 'delivered_at_record')
    op.drop_column('orders', 'offer_id')
    op.drop_constraint(None, 'offers', type_='foreignkey')
    op.drop_column('offers', 'order_id')
    # ### end Alembic commands ###
