"""sync_orders_columns

Revision ID: fc157c202cf2
Revises: 20260605_return
Create Date: 2026-06-08 14:28:16.911969

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'fc157c202cf2'
down_revision = '20260605_return'
branch_labels = None
depends_on = None


def column_exists(table: str, column: str) -> bool:
    bind = op.get_bind()
    result = bind.execute(
        sa.text(
            "SELECT EXISTS (SELECT 1 FROM information_schema.columns "
            f"WHERE table_name = '{table}' AND column_name = '{column}')"
        )
    )
    return result.scalar()


def constraint_exists(constraint_name: str) -> bool:
    bind = op.get_bind()
    result = bind.execute(
        sa.text(
            "SELECT EXISTS (SELECT 1 FROM information_schema.table_constraints "
            f"WHERE constraint_name = '{constraint_name}')"
        )
    )
    return result.scalar()


def index_exists(index_name: str) -> bool:
    bind = op.get_bind()
    result = bind.execute(
        sa.text(
            "SELECT EXISTS (SELECT 1 FROM pg_indexes "
            f"WHERE indexname = '{index_name}')"
        )
    )
    return result.scalar()


def create_enum(enum_name: str, values: list[str]) -> None:
    bind = op.get_bind()
    result = bind.execute(
        sa.text(f"SELECT EXISTS (SELECT 1 FROM pg_type WHERE typname = '{enum_name}')")
    )
    if not result.scalar():
        values_str = ", ".join(f"'{v}'" for v in values)
        bind.execute(sa.text(f"CREATE TYPE {enum_name} AS ENUM ({values_str})"))


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if not column_exists('offers', 'order_id'):
        op.add_column('offers', sa.Column('order_id', sa.Uuid(), nullable=True))
        op.create_foreign_key(None, 'offers', 'orders', ['order_id'], ['id'], ondelete='SET NULL')
    
    if not column_exists('orders', 'offer_id'):
        op.add_column('orders', sa.Column('offer_id', sa.Uuid(), nullable=True))
    if not column_exists('orders', 'delivered_at_record'):
        op.add_column('orders', sa.Column('delivered_at_record', sa.DateTime(), nullable=True))
    if not column_exists('orders', 'auto_complete_at'):
        op.add_column('orders', sa.Column('auto_complete_at', sa.DateTime(), nullable=True))
    if not column_exists('orders', 'auto_release_at'):
        op.add_column('orders', sa.Column('auto_release_at', sa.DateTime(), nullable=True))
    if not column_exists('orders', 'payment_method'):
        op.add_column('orders', sa.Column('payment_method', sa.VARCHAR(length=20), nullable=False, server_default='WALLET'))
    if not column_exists('orders', 'tracking_number'):
        op.add_column('orders', sa.Column('tracking_number', sa.VARCHAR(), nullable=True))

    create_enum('orderstatus', ['PENDING', 'CONFIRMED', 'SHIPPING', 'DELIVERED', 'DELIVERY_FAILED', 'RETURNING', 'RETURNED', 'COMPLETED', 'CANCELLED'])
    create_enum('paymentmethod', ['WALLET', 'COD'])

    op.alter_column('orders', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('PENDING', 'CONFIRMED', 'SHIPPING', 'DELIVERED', 'DELIVERY_FAILED', 'RETURNING', 'RETURNED', 'COMPLETED', 'CANCELLED', name='orderstatus'),
               nullable=False,
               postgresql_using="upper(status)::orderstatus")
    op.alter_column('orders', 'payment_method', server_default=None)
    op.alter_column('orders', 'payment_method',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('WALLET', 'COD', name='paymentmethod'),
               existing_nullable=False,
               postgresql_using="upper(payment_method)::paymentmethod")
    op.alter_column('orders', 'payment_method',
               server_default=sa.text("'WALLET'::paymentmethod"))

    if index_exists('ix_orders_tracking_number'):
        op.drop_index(op.f('ix_orders_tracking_number'), table_name='orders')
    if not index_exists('ix_orders_buyer_id'):
        op.create_index(op.f('ix_orders_buyer_id'), 'orders', ['buyer_id'], unique=False)
    if not index_exists('ix_orders_seller_id'):
        op.create_index(op.f('ix_orders_seller_id'), 'orders', ['seller_id'], unique=False)

    for fk in ['orders_listing_id_fkey', 'orders_seller_id_fkey', 'orders_buyer_id_fkey']:
        if constraint_exists(fk):
            op.drop_constraint(op.f(fk), 'orders', type_='foreignkey')

    op.create_foreign_key(None, 'orders', 'listings', ['listing_id'], ['id'])
    op.create_foreign_key(None, 'orders', 'offers', ['offer_id'], ['id'])
    op.create_foreign_key(None, 'orders', 'users', ['seller_id'], ['id'])
    op.create_foreign_key(None, 'orders', 'users', ['buyer_id'], ['id'])

    if not column_exists('wallet_transactions', 'status'):
        op.add_column('wallet_transactions', sa.Column('status', sa.VARCHAR(length=20), nullable=False, server_default='completed'))

    op.alter_column('wallet_transactions', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'completed'::character varying"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wallet_transactions', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'completed'::character varying"))

    for fk in ['orders_buyer_id_fkey', 'orders_seller_id_fkey', 'orders_listing_id_fkey']:
        if not constraint_exists(fk):
            op.create_foreign_key(op.f(fk), 'orders', 'users', ['buyer_id'], ['id'], ondelete='CASCADE')
            op.create_foreign_key(op.f(fk), 'orders', 'users', ['seller_id'], ['id'], ondelete='CASCADE')
            op.create_foreign_key(op.f(fk), 'orders', 'listings', ['listing_id'], ['id'], ondelete='CASCADE')

    if index_exists('ix_orders_seller_id'):
        op.drop_index(op.f('ix_orders_seller_id'), table_name='orders')
    if index_exists('ix_orders_buyer_id'):
        op.drop_index(op.f('ix_orders_buyer_id'), table_name='orders')
    if not index_exists('ix_orders_tracking_number'):
        op.create_index(op.f('ix_orders_tracking_number'), 'orders', ['tracking_number'], unique=False)

    op.alter_column('orders', 'payment_method',
               existing_type=sa.Enum('WALLET', 'COD', name='paymentmethod'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'wallet'::character varying"))
    op.alter_column('orders', 'status',
               existing_type=sa.Enum('PENDING', 'CONFIRMED', 'SHIPPING', 'DELIVERED', 'DELIVERY_FAILED', 'RETURNING', 'RETURNED', 'COMPLETED', 'CANCELLED', name='orderstatus'),
               type_=sa.VARCHAR(length=50),
               nullable=True)

    if column_exists('orders', 'auto_release_at'):
        op.drop_column('orders', 'auto_release_at')
    if column_exists('orders', 'auto_complete_at'):
        op.drop_column('orders', 'auto_complete_at')
    if column_exists('orders', 'delivered_at_record'):
        op.drop_column('orders', 'delivered_at_record')
    if column_exists('orders', 'offer_id'):
        op.drop_column('orders', 'offer_id')
    if column_exists('offers', 'order_id'):
        op.drop_column('offers', 'order_id')
    # ### end Alembic commands ###
